changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - "breaking-change"
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Docs
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
    - title: Other
      labels:
        - "*"
